### ISSUE TITLE
请问是playsound导致的问题吗？

### ISSUE THREAD

**Issue by xia1001** [greatcodeeer/iPhone-Pickup-Monitor#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 261, in <module>
    playsound(argv[1])
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 163, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    playsound(sound_alarm)
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 254, in <lambda>
    playsound = lambda sound, block = True: _playsoundAnotherPython('/usr/bin/python3', sound, block, macOS = False)
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 229, in _playsoundAnotherPython
    t.join()
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 218, in join
    raise self.exc
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 211, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/playsound.py", line 226, in <lambda>
    t = PropogatingThread(target = lambda: check_call([otherPython, playsoundPath, _handlePathOSX(sound) if macOS else sound]))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/local/lib/python3.7/dist-packages/playsound.py', './alarm.mp3']' returned non-zero exit status 1.

**Comment by greatcodeeer** [comment]
确实是playsound的问题。python下音频播放一直没有太好的方案，即使是playsound这种兼容性比较强的也有不少bug。
尝试下安装 python3-gst-1.0 库：
`sudo apt install python3-gst-1.0`
参考：https://github.com/TaylorSMarks/playsound/issues/16#issuecomment-658182306
