### ISSUE TITLE
m1运行报错

### ISSUE THREAD

**Issue by shenfu1991** [greatcodeeer/iPhone-Pickup-Monitor#6]
环境安装看起来正常的/？
<pre>
shenfu@shenfus-Mac-mini iPhone-Pickup-Monitor % pip3 install -r requirements.txt
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: playsound==1.3.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: requests==2.26.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (3.3)
WARNING: You are using pip version 21.2.4; however, version 21.3 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

</pre>

<pre>
shenfu@shenfus-Mac-mini iPhone-Pickup-Monitor % python3 run.py
playsound is relying on a python 2 subprocess. Please use `pip3 install PyObjC` if you want playsound to run more efficiently.
欢迎使用iPhone取货预约助手，请合理使用工具
正在检查环境：
即将播放预约提示音，按任意键开始...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 261, in <module>
    playsound(argv[1])
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 119, in _playsoundOSX
    from AppKit import NSSound
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/AppKit/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 28, in <module>
    from objc._bridgesupport import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/shenfu/iPhone-Pickup-Monitor/run.py", line 15, in <module>
    playsound(sound_alarm)
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 244, in <lambda>
    playsound = lambda sound, block = True: _playsoundAnotherPython('/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', sound, block, macOS = True)
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 229, in _playsoundAnotherPython
    t.join()
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 218, in join
    raise self.exc
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 211, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/playsound.py", line 226, in <lambda>
    t = PropogatingThread(target = lambda: check_call([otherPython, playsoundPath, _handlePathOSX(sound) if macOS else sound]))
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', '/opt/homebrew/lib/python3.9/site-packages/playsound.py', 'file:///Users/shenfu/iPhone-Pickup-Monitor/./alarm.mp3']' returned non-zero exit status 1.

</pre>

**Comment by greatcodeeer** [comment]
正如 playsound 给出的提示 “使用 pip3 install PyObjC 安装一下”
